source "https://rubygems.org"

ruby "~> 3.2"

gem "jekyll", "~> 4.3"

# Force a newer eventmachine that works on ARM/Ruby 3.2
gem "eventmachine", "~> 1.2", ">= 1.2.8"

group :jekyll_plugins do
  gem "jekyll-feed"
  gem "jekyll-seo-tag"
  gem "jekyll-sitemap"
end
